Dev 3127 update tests
Expedient/is-dev-workflows pull request #22
Opened 2023-04-24 23:36 UTC by geoff-maddock

2023-04-25 20:22 UTC, spencerp98 submitted a review, later dismissed

2023-04-25 20:22 UTC, spencerp98 commented on .github/workflows/newman-k8s-tests.yml
> +          kubectl exec deploy/${{inputs.APPLICATION}} -c newman -- newman run postman/${{inputs.APPLICATION}}${{inputs.TEST_SUFFIX}}.postman_collection.json -e postman/${{inputs.APPLICATION}}.postman
```suggestion
          kubectl exec deploy/${{inputs.APPLICATION}} -c newman -- newman run .postman/${{inputs.APPLICATION}}${{inputs.TEST_SUFFIX}}.postman_collection.json -e .postman/${{inputs.APPLICATION}}.postman_environment.json --verbose
```

2023-04-26 16:56 UTC, geoff-maddock commented
Hold before merging this.   Running into an issue where we can't select .postman in postman as a location for the collections

2023-05-02 16:57 UTC, spencerp98 approved these changes

2023-05-02 17:00 UTC, spencerp98 requested changes

2023-05-02 17:00 UTC, spencerp98 commented on .github/workflows/newman-k8s-tests.yml
> +          kubectl exec deploy/${{inputs.APPLICATION}} -c newman -- newman run postman/${{inputs.APPLICATION}}${{inputs.TEST_SUFFIX}}.postman_collection.json -e postman/${{inputs.APPLICATION}}.postman
```suggestion
          kubectl exec deploy/${{inputs.APPLICATION}} -c newman -- newman run postman/collections/${{inputs.APPLICATION}}${{inputs.TEST_SUFFIX}}.postman_collection.json -e postman/environments/${{inputs.APPLICATION}}.postman_environment.json --verbose
```

2023-05-02 18:41 UTC, spencerp98 approved these changes

2023-05-02 18:41 UTC, merged